# Generated by Django 4.1.2 on 2023-08-25 10:46

import account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', account.models.CustomManager()),
            ],
        ),
    ]
